version: '3.8' # Используем актуальную версию Compose

services:
  # --- Сервис: Бэкенд (Spring Boot приложение) ---
#  backend-app:
#    build: .
#    container_name: truck_backend
#    restart: on-failure
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/truckdb
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
#      - GRAPHHOPPER_API_KEY=${GRAPHHOPPER_API_KEY}
#      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
#    depends_on:
#      - database
#    networks:
#      - truck_network

  # --- Сервис: База данных (PostgreSQL + PostGIS) ---
  database:
    image: postgis/postgis:15-3.4
    container_name: truck_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=truckdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - truck_network

# --- Декларация именованных volumes ---
volumes:
  postgres_data:

# --- Декларация сети ---
networks:
  truck_network:
    driver: bridge # Стандартный тип сети для Docker Compose